# Generated by Django 6.0.8 on 2026-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotline_wholesale', models.CharField(default='[số hotline sỉ]', max_length=60, verbose_name='Hotline sỉ')),
                ('hotline_retail', models.CharField(default='[số hotline lẻ]', max_length=60, verbose_name='Hotline lẻ')),
                ('email', models.CharField(default='[email]', max_length=120, verbose_name='Email liên hệ')),
                ('zalo_oa', models.CharField(default='[tên Zalo OA]', max_length=120, verbose_name='Tên Zalo OA')),
                ('tax_code', models.CharField(default='[MST]', max_length=60, verbose_name='Mã số thuế')),
                ('business_license_no', models.CharField(default='[số]', max_length=60, verbose_name='Số ĐKKD')),
                ('business_license_date', models.CharField(default='[ngày]', max_length=60, verbose_name='Ngày cấp ĐKKD')),
                ('business_license_issuer', models.CharField(default='[nơi cấp]', max_length=120, verbose_name='Nơi cấp ĐKKD')),
                ('head_office_address', models.CharField(default='[địa chỉ trụ sở]', max_length=255, verbose_name='Địa chỉ trụ sở')),
                ('warehouse_address', models.CharField(default='[địa chỉ kho]', max_length=255, verbose_name='Địa chỉ kho')),
                ('warehouse_area', models.CharField(default='[diện tích]', max_length=60, verbose_name='Diện tích kho')),
                ('shopee_url', models.CharField(default='[link]', max_length=255, verbose_name='Link Shopee Mall')),
                ('lazada_url', models.CharField(default='[link]', max_length=255, verbose_name='Link LazMall')),
                ('tiktok_url', models.CharField(default='[link]', max_length=255, verbose_name='Link TikTok Shop')),
                ('moit_notice', models.CharField(default='[bổ sung sau khi hoàn tất thông báo tại online.gov.vn]', max_length=255, verbose_name='Ghi chú Bộ Công Thương')),
                ('founded_year', models.CharField(default='[năm thành lập]', max_length=60, verbose_name='Năm thành lập')),
                ('retail_points', models.CharField(default='[số điểm bán]', max_length=60, verbose_name='Số điểm bán')),
                ('staff_count', models.CharField(default='[nhân sự]', max_length=60, verbose_name='Nhân sự')),
                ('coverage', models.CharField(default='[số tỉnh/thành]', help_text='Chỉ nhập con số. Câu chữ đã có sẵn: "ghép chuyến giao ___ tỉnh/thành".', max_length=120, verbose_name='Số tỉnh/thành phủ hàng')),
                ('shipping_partner', models.CharField(default='[tên đơn vị]', max_length=120, verbose_name='Đối tác vận chuyển')),
                ('facility_location', models.CharField(default='[địa điểm]', help_text='Hiển thị trên thẻ số liệu, ví dụ "TP.HCM". Địa chỉ đầy đủ nhập ở ô "Địa chỉ kho".', max_length=120, verbose_name='Địa điểm kho (tên ngắn)')),
            ],
            options={
                'verbose_name': 'Thông tin doanh nghiệp',
                'verbose_name_plural': 'Thông tin doanh nghiệp',
            },
        ),
    ]
