# Generated by Django 6.0.8 on 2026-08-25 09:31

import apps.common.images
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Đường dẫn')),
                ('topic', models.CharField(choices=[('Tin công ty', 'Tin công ty'), ('Chương trình đại lý', 'Chương trình đại lý'), ('Kiến thức sản phẩm', 'Kiến thức sản phẩm')], default='Tin công ty', max_length=40, verbose_name='Chuyên mục')),
                ('cover', models.ImageField(blank=True, upload_to='news/', validators=[apps.common.images.validate_upload_size], verbose_name='Ảnh bìa')),
                ('cover_alt', models.CharField(blank=True, help_text='Bắt buộc nếu có ảnh bìa.', max_length=200, verbose_name='Mô tả ảnh bìa (alt)')),
                ('excerpt', models.TextField(blank=True, max_length=400, verbose_name='Tóm tắt')),
                ('body', tinymce.models.HTMLField(blank=True, verbose_name='Nội dung')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm đăng')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đã đăng')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='news_articl_is_publ_0ea520_idx')],
            },
        ),
    ]
