# Generated by Django 6.0.8 on 2026-08-25 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=120, verbose_name='Họ và tên')),
                ('sdt', models.CharField(db_index=True, max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('zalo', models.CharField(blank=True, max_length=40, verbose_name='Zalo')),
                ('previous_count', models.PositiveIntegerField(default=0, editable=False, help_text='Đếm tự động theo số điện thoại, tính cả form liên hệ và form đại lý.', verbose_name='Số lần đã gửi trước đó')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='Nguồn (utm_source)')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='Kênh (utm_medium)')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='Chiến dịch (utm_campaign)')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Đến từ trang')),
                ('landing_page', models.CharField(blank=True, max_length=500, verbose_name='Trang vào đầu tiên')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('contacted', 'Đã liên hệ'), ('won', 'Chốt được'), ('rejected', 'Không phù hợp')], default='new', max_length=12, verbose_name='Trạng thái')),
                ('internal_note', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Đã báo Telegram')),
                ('telegram_error', models.TextField(blank=True, verbose_name='Lỗi Telegram')),
                ('telegram_message_id', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Mã tin nhắn Telegram')),
                ('chude', models.CharField(choices=[('Báo giá sỉ', 'Báo giá sỉ'), ('Hàng chính hãng', 'Hàng chính hãng'), ('Khác', 'Khác')], default='Báo giá sỉ', max_length=40, verbose_name='Cần hỗ trợ về')),
                ('noidung', models.TextField(blank=True, verbose_name='Nội dung')),
            ],
            options={
                'verbose_name': 'Lời nhắn liên hệ',
                'verbose_name_plural': 'Lời nhắn liên hệ',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=120, verbose_name='Họ và tên')),
                ('sdt', models.CharField(db_index=True, max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('zalo', models.CharField(blank=True, max_length=40, verbose_name='Zalo')),
                ('previous_count', models.PositiveIntegerField(default=0, editable=False, help_text='Đếm tự động theo số điện thoại, tính cả form liên hệ và form đại lý.', verbose_name='Số lần đã gửi trước đó')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='Nguồn (utm_source)')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='Kênh (utm_medium)')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='Chiến dịch (utm_campaign)')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Đến từ trang')),
                ('landing_page', models.CharField(blank=True, max_length=500, verbose_name='Trang vào đầu tiên')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('contacted', 'Đã liên hệ'), ('won', 'Chốt được'), ('rejected', 'Không phù hợp')], default='new', max_length=12, verbose_name='Trạng thái')),
                ('internal_note', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Đã báo Telegram')),
                ('telegram_error', models.TextField(blank=True, verbose_name='Lỗi Telegram')),
                ('telegram_message_id', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Mã tin nhắn Telegram')),
                ('donvi', models.CharField(blank=True, max_length=200, verbose_name='Đơn vị / cửa hàng')),
                ('khuvuc', models.CharField(blank=True, choices=[('Hà Nội', 'Hà Nội'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Đà Nẵng', 'Đà Nẵng'), ('Cần Thơ', 'Cần Thơ'), ('Hải Phòng', 'Hải Phòng'), ('Tỉnh / thành khác…', 'Tỉnh / thành khác…')], max_length=40, verbose_name='Khu vực kinh doanh')),
                ('loaihinh', models.CharField(blank=True, choices=[('Đại lý / nhà bán buôn', 'Đại lý / nhà bán buôn'), ('Siêu thị / cửa hàng tiện lợi', 'Siêu thị / cửa hàng tiện lợi'), ('Tạp hóa / cửa hàng lẻ', 'Tạp hóa / cửa hàng lẻ'), ('HORECA (nhà hàng, café, khách sạn)', 'HORECA (nhà hàng, café, khách sạn)'), ('Bán hàng online / sàn TMĐT', 'Bán hàng online / sàn TMĐT')], max_length=60, verbose_name='Loại hình kinh doanh')),
                ('sanluong', models.CharField(blank=True, choices=[('Dưới 10 thùng', 'Dưới 10 thùng'), ('10–50 thùng', '10–50 thùng'), ('Trên 50 thùng', 'Trên 50 thùng')], max_length=20, verbose_name='Sản lượng dự kiến / tháng')),
                ('completion_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Mã bước 2')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Đã điền đủ bước 2')),
            ],
            options={
                'verbose_name': 'Đăng ký đại lý',
                'verbose_name_plural': 'Đăng ký đại lý',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
