# Generated by Django 6.0.8 on 2026-08-25 09:27

import apps.common.images
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Đang được dùng để lọc sản phẩm trên trang. Đổi giá trị này sẽ làm bộ lọc ngừng hoạt động.', max_length=80, unique=True, verbose_name='Tên thương hiệu')),
                ('name_cn', models.CharField(blank=True, max_length=80, verbose_name='Tên tiếng Trung')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Đường dẫn')),
                ('logo', models.ImageField(blank=True, upload_to='brands/', validators=[apps.common.images.validate_upload_size], verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, help_text='Bỏ chọn nếu Life Nutrition chưa phân phối thương hiệu này.', verbose_name='Đang phân phối')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Thương hiệu',
                'verbose_name_plural': 'Thương hiệu',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Tên hiển thị trên bộ lọc')),
                ('short_name', models.CharField(help_text='Hiển thị trên thẻ sản phẩm, ví dụ: Bánh quy.', max_length=40, verbose_name='Tên ngắn')),
                ('slug', models.SlugField(help_text='Đang được dùng để lọc sản phẩm trên trang. Đổi giá trị này sẽ làm bộ lọc ngừng hoạt động.', max_length=40, unique=True, verbose_name='Mã ngành hàng')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Ngành hàng',
                'verbose_name_plural': 'Ngành hàng',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Đường dẫn')),
                ('image', models.ImageField(upload_to='products/', validators=[apps.common.images.validate_upload_size], verbose_name='Ảnh sản phẩm')),
                ('image_alt', models.CharField(help_text='Bắt buộc — dùng cho trình đọc màn hình và SEO.', max_length=200, verbose_name='Mô tả ảnh (alt)')),
                ('description', models.CharField(blank=True, help_text='Dòng chữ Hoa và danh sách vị, ví dụ: 果味茶 · đào trắng ô long / nho xanh trà xanh.', max_length=255, verbose_name='Tên gốc / biến thể')),
                ('packaging', models.CharField(blank=True, help_text='Ví dụ: Chai 500ml · thùng 15 chai.', max_length=160, verbose_name='Quy cách')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Thương hiệu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Ngành hàng')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='catalog_pro_is_acti_903fcc_idx')],
            },
        ),
    ]
