# Generated by Django 6.0.8 on 2026-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Bỏ chọn nếu chưa phân phối thương hiệu này.', verbose_name='Đang phân phối'),
        ),
    ]
