# Generated by Django 6.0.8 on 2026-09-06 17:39

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=tinymce.models.HTMLField(blank=True, help_text='Bài giới thiệu dài trên trang chi tiết sản phẩm. Có thể chèn ảnh trực tiếp vào bài.', verbose_name='Nội dung chi tiết'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Tối đa 160 ký tự. Bỏ trống để tự ghép từ hai dòng chữ trên thẻ sản phẩm.', max_length=160, verbose_name='Mô tả SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Tối đa 70 ký tự. Bỏ trống để dùng: Tên sản phẩm — Thương hiệu | Dali Foods Việt Nam.', max_length=70, verbose_name='Tiêu đề SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc'),
        ),
    ]
